CREATE TABLE SHIPWRECK(
	Id INT default nextval('idwebuser_id_seq'),
	NAME VARCHAR(295),
	DESCRIPTION VARCHAR(2000),
	CONDITION VARCHAR(255),
	DEPTH INT,
	LATITUDE INT,
	LONGITUDE INT,
	YEAR_DISCOVERED INT
);